logging:
  config: classpath:spring-logback.xml
test:
   url: https://192.168.31.128/ui/login.action
   user: admin
   password: Simple@0
   file: D:\project\FusionDirector\mosai_gitlab\fd-vrealize-plugin\src\huawei-fusion-director-management-pack\build\deploy\HuaweiFusionDirectorManagementPack_1.0.1.pak
   fd:
     name: host_192.168.31.1
     host: 192.168.31.1
     port: 32102
     user: rootRedfish
     pass: Machine@123
     configBtnId: objectNavigatorToolbarAdministrationBtn
browser:
  driver: c:\\chromedriver-72.exe